#nome do projeto
name: ci-golang-workflow
#toda vez que eu der um push o que vai acontecer?
on:
  pull_request:
    branches:
      - develop
#ira rodar esse jobb
jobs:
  check-application:
    #onde vai rodar
    runs-on: ubuntu-latest
    #passos que vai ser executado
    steps:
      # Uses: repositório/Action
      #faz o checkout do código do seu repositório dentro do runner do GitHub Actions      
      - uses: actions/checkout@v3
      #configura um ambiente Go no runner
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      #rodar comando    
      - run: go test
      - run: go run math.go